# permissions for end users to edit klusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder-bookapi
    app.kubernetes.io/managed-by: kustomize
  name: kluster-editor-role
rules:
- apiGroups:
  - core.pulok.dev
  resources:
  - klusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.pulok.dev
  resources:
  - klusters/status
  verbs:
  - get
